### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GitHubUser2069** [SebyPlays/LogManagerAPI#1]
If i start the LogManager,
ther is an Error: 
java.io.IOException: No such file or directory
pleas fix this.

**Comment by CheeseTastisch** [comment]
Hey,

i thik, your user has no rights to the directory "/logs"

On what user your API is running?

**Comment by GitHubUser2069** [comment]
I run the API white an own user, named DonaldTrump.
Command to set the rigths?

**Comment by CheeseTastisch** [comment]
cd /
chown -R DonaldTrump:DonaldTrump logs/
